language: node_js
node_js:
  - 12

addons:
  hosts:
    - host.docker.internal

services:
  - docker

before_script:
  - docker-compose up
  - npm link
  - npm link restheart-client
  - npm run build:prod

install: true

