language: node_js
node_js:
  - 12

services:
  - docker
  - mongodb

before_script:
  - sleep 15
  - docker-compose up
  - npm link
  - npm link restheart-client
  - npm run build:prod

install: true

