version: "2"
services:

  mongo:
    image: mongo:3.6
    ports:
      - "49207:27017"
    volumes:
      - ./test/resources/mongo:/opt/mongo
      - ./test/resources/mongo/restore.sh:/docker-entrypoint-initdb.d/restore.sh:ro

  sleep10:
    image: alpine:latest
    depends_on:
      - mongo
    command: "sleep 10"

  restheart:
    image: softinstigate/restheart:3.10.0
    depends_on:
      - sleep10
    volumes:
      - ./test/resources/restheart/v3/config.properties:/opt/restheart/etc/config.properties
      - ./test/resources/restheart/v3/restheart.yml:/opt/restheart/etc/restheart.yml
    ports:
      - "5151:8080"